services:
  samba:
    build: .
    container_name: DebianSambaDC
    environment:
      - SAMBA_DOMAIN=CYBERBEAN
      - SAMBA_REALM=SAMDOM.CYBERBEAN.COM
      - SAMBA_ADMIN_PASSWORD=Admin66
      - KERBEROS_PASSWORD=Kerberos1
      - KRB5_CONFIG=/etc/krb5/krb5.conf
    volumes:
      - ./conf/bind:/etc/bind
      - ./conf/samba:/etc/samba
      - ./conf/krb5:/etc/krb5
      - ./data/samba:/var/lib/samba
      - ./data/krb5:/var/lib/krb5kdc
    ports:
      - "22:22"
      - "53:53"
      - "389:389"
      - "88:88"
      - "135:135"
      - "139:139"
      - "138:138"
      - "445:445"
      - "464:464"
      - "3268:3268"
      - "3269:3269"
